'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {KeyRound} from 'lucide-react';
import {Button} from './ui/button';
import {supabase} from '@/lib/supabase';
import {validateAccount} from '@/lib/passwords';
import type {CareState,Caregiver} from '@/lib/domain';
export function PasswordAccountsPanel({state,current,onSaved}:{state:CareState;current:Caregiver;onSaved:()=>Promise<void>}){
 const [target,setTarget]=useState(current.id);const [names,setNames]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 const selected=state.caregivers.find(c=>c.id===target)||current;
 async function load(){const {data,error}=await supabase!.rpc('family_login_names',{p_patient:state.patientId});if(error)setError(error.message);else setNames(Object.fromEntries((data||[]).map((r:{id:string;username:string})=>[r.id,r.username])))}
 useEffect(()=>{void load()},[state.patientId]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);const username=String(fd.get('username')).trim().toLowerCase();const password=String(fd.get('password'));setBusy(true);setError('');setSuccess('');try{validateAccount(username,password);if(password!==String(fd.get('confirm')))throw Error('Les deux mots de passe ne correspondent pas.');const {data,error}=await supabase!.functions.invoke('family-accounts',{body:{action:'save',patientId:state.patientId,targetId:target,email:String(fd.get('email')).trim().toLowerCase(),username,password}});if(error){let message='Impossible de mettre à jour ce compte.';try{message=(await error.context?.json())?.error||message}catch{}throw Error(message)}if(data?.error)throw Error(data.error);form.reset();await load();await onSaved();setTarget(current.id);setSuccess('Compte enregistré. Communiquez directement à cette personne son identifiant et son mot de passe. Aucun e-mail n’est nécessaire.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="invite-section"><h3><KeyRound size={18}/> Identifiants et mots de passe</h3><p className="muted">1. Choisissez le compte ci-dessous. 2. Renseignez l’adresse e-mail et l’identifiant. 3. Saisissez deux fois le mot de passe, puis enregistrez. Les mots de passe existants ne sont jamais affichés.</p><form onSubmit={save}><label>Compte à gérer<select value={target} onChange={e=>{setTarget(e.target.value);setError('');setSuccess('')}}>{state.caregivers.filter(c=>c.id===current.id||c.role==='aidant').map(c=><option key={c.id} value={c.id}>{c.name}{c.id===current.id?' (mon compte)':''}</option>)}</select></label><div key={target+names[target]}><label>Adresse e-mail liée<input type="email" name="email" defaultValue={selected.email||''} readOnly={selected.registered!==false} required maxLength={254} autoComplete="off"/></label><label>Identifiant de connexion<input name="username" defaultValue={names[target]||''} required minLength={3} maxLength={40} pattern="[a-z0-9._\-]{3,40}" autoComplete="off" autoCapitalize="none" placeholder="identifiant personnel"/></label><p className="small muted">Identifiant : 3 à 40 caractères, en minuscules, sans espace (lettres, chiffres, point, tiret ou underscore). Mot de passe : au moins 10 caractères.</p><label>{selected.registered===false?'Mot de passe initial':'Nouveau mot de passe'}<input name="password" type="password" required minLength={10} maxLength={72} autoComplete="new-password"/></label><label>Confirmer le mot de passe<input name="confirm" type="password" required minLength={10} maxLength={72} autoComplete="new-password"/></label></div><Button disabled={busy}>{busy?'Enregistrement…':selected.registered===false?'Créer le compte':'Enregistrer les accès'}</Button></form><p className="small muted">La connexion accepte l’identifiant ou l’adresse e-mail. En cas d’oubli, vous définissez un nouveau mot de passe ici.</p>{error&&<p role="alert" className="error">{error}</p>}{success&&<p role="status" className="panel-success">{success}</p>}</section>
}
