export type Caregiver={id:string;name:string;initial:string;color:number;role:'admin'|'aidant';email?:string;registered?:boolean};
export type Medication={example?:boolean;id:string;name:string;detail:string;times:string[];active?:boolean};
export type Symptom={example?:boolean;id:string;createdAt:string;caregiverId:string;scores:Record<string,number>;phase:string;note:string};
export type Message={example?:boolean;id:string;createdAt:string;caregiverId:string;text:string;kind:'message'|'note'};
export type Visit={example?:boolean;id:string;date:string;caregiverId:string;report?:string;note?:string;weekStart?:string;cancelled?:boolean;imported?:boolean;inferred?:boolean};
export type Exchange={id:string;visitId:string;targetId:string;requesterId:string;status:'pending'|'accepted'|'declined'};
export type ExampleData=Pick<CareState,'medications'|'consultations'|'symptoms'|'messages'|'visits'>;
export type CareState={examples?:ExampleData;patientId:string;patientName:string;caregivers:Caregiver[];medications:Medication[];consultations:Consultation[];symptoms:Symptom[];messages:Message[];visits:Visit[];exchanges:Exchange[];unavailable:{date:string;caregiverId:string}[]};
export function localDate(d=new Date()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Brussels',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
export function localTime(d=new Date()){return new Intl.DateTimeFormat('fr-BE',{timeZone:'Europe/Brussels',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)}
export function dateLabel(date:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'long'}){return new Intl.DateTimeFormat('fr-BE',{timeZone:'Europe/Brussels',...options}).format(new Date(date+'T12:00:00Z'))}
export function sundayDates(start:string,count=8){const d=new Date(start+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+(7-d.getUTCDay())%7);return Array.from({length:count},(_,i)=>{const copy=new Date(d);copy.setUTCDate(d.getUTCDate()+i*7);return copy.toISOString().slice(0,10)})}
export function rotate(dates:string[],caregivers:Caregiver[],unavailable:CareState['unavailable'],prior:Visit[]=[]):Visit[]{const counts=Object.fromEntries(caregivers.map(c=>[c.id,prior.filter(v=>v.caregiverId===c.id).length]));let cursor=prior.length%caregivers.length;return dates.map(date=>{const available=caregivers.filter(c=>!unavailable.some(u=>u.date===date&&u.caregiverId===c.id));if(!available.length)return {id:date,date,caregiverId:''};available.sort((a,b)=>counts[a.id]-counts[b.id]||((caregivers.indexOf(a)-cursor+caregivers.length)%caregivers.length)-((caregivers.indexOf(b)-cursor+caregivers.length)%caregivers.length));const selected=available[0];counts[selected.id]++;cursor=(caregivers.indexOf(selected)+1)%caregivers.length;return {id:date,date,caregiverId:selected.id}})}
export type Consultation={example?:boolean;id:string;date:string;createdAt:string;caregiverId:string;doctor:string;specialty:string;observations:string;followUp:string};
export function validateTimes(value:string){const times=value.split(/[,;\s]+/).map(s=>s.trim()).filter(Boolean);if(!times.length||times.length>12||times.some(t=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(t)))throw Error('Indiquez de 1 à 12 horaires au format HH:mm, par exemple 08:00, 12:00.');return [...new Set(times)].sort()}
