export type PlanningRow={date:string;weekStart?:string;name:string;note:string;cancelled:boolean;inferred:boolean;sourceRow:number};
export type PlanningPreview={rows:PlanningRow[];warnings:string[];names:string[]};
const clean=(v:unknown)=>String(v??'').trim();
export const nameKey=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
export function isoDate(value:unknown):string|null{
 if(value instanceof Date&&!Number.isNaN(value.getTime()))return value.toISOString().slice(0,10);
 const s=clean(value);let y:number,m:number,d:number;let match=s.match(/^(\d{4})-(\d{2})-(\d{2})(?:T.*)?$/);
 if(match){y=+match[1];m=+match[2];d=+match[3]}else{match=s.match(/^(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{4})$/);if(!match)return null;d=+match[1];m=+match[2];y=+match[3]}
 const date=new Date(Date.UTC(y,m-1,d));return y>=2000&&y<=2100&&date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d?date.toISOString().slice(0,10):null;
}
function addDays(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
export function delimited(text:string):unknown[][]{
 const first=text.split(/\r?\n/).find(l=>l.trim())||'';const sep=first.includes('\t')?'\t':first.includes(';')?';':',';const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===sep&&!quoted){row.push(cell);cell=''}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}
 if(quoted)throw Error('Une cellule entre guillemets n’est pas fermée.');if(cell||row.length){row.push(cell);rows.push(row)}return rows;
}
export function previewPlanning(grid:unknown[][]):PlanningPreview{
 const warnings:string[]=[];const rows:PlanningRow[]=[];const hi=grid.findIndex(r=>r.some(v=>/date|semaine/i.test(clean(v)))&&r.some(v=>/aidant|qui|responsable|nom/i.test(clean(v))));if(hi<0)throw Error('Ajoutez une ligne d’en-tête avec Date (ou Semaine du lundi), Aidant (ou Qui ?) et Commentaire.');
 const headers=grid[hi].map(v=>nameKey(clean(v)));const dc=headers.findIndex(v=>/date|semaine/.test(v));const nc=headers.findIndex(v=>/aidant|qui|responsable|nom/.test(v));let cc=headers.findIndex(v=>/comment|note|agenda|observation/.test(v));if(cc===dc||cc===nc)cc=-1;const weekly=/semaine/.test(headers[dc]);const fullNames=[...new Set(grid.slice(hi+1).map(r=>clean(r[nc])).filter(n=>n.length>3&&!/^[-–—]$/.test(n)))];
 if(grid.length-hi>1002)throw Error('Limite : 1 000 lignes par import.');
 for(let i=hi+1;i<grid.length;i++){
 const r=grid[i];if(!r.some(v=>clean(v)))continue;const start=isoDate(r[dc]);if(!start){warnings.push(`Ligne ${i+1} ignorée : date absente ou invalide.`);continue}let name=clean(r[nc]);const note=cc>=0?clean(r[cc]):'';const candidates=fullNames.filter(n=>nameKey(n).startsWith(nameKey(name)));if(name&&name.length<=3&&candidates.length===1){const previous=name;name=candidates[0];warnings.push(`Ligne ${i+1} : « ${previous} » devient « ${name} ».`)}const cancelled=/^[-–—]$/.test(name)||/pas de visite/i.test(note);if(cancelled)name='';if(!name&&!cancelled){warnings.push(`Ligne ${i+1} ignorée : aidant absent.`);continue}if(name.length>80||note.length>5000)throw Error(`Ligne ${i+1} : prénom ou commentaire trop long.`);
 let date=start,inferred=false;if(weekly){if(new Date(start+'T12:00:00Z').getUTCDay()!==1)throw Error(`Ligne ${i+1} : la semaine doit commencer un lundi.`);date=addDays(start,6);inferred=true;const visitDay=note.match(/^\s*(lundi|mardi|mercredi|jeudi|vendredi|samedi|dimanche)\s+(\d{1,2})(?:\/(\d{1,2}))?/i);if(visitDay&&!/neuro|médec|medec|consult|rdv|rendez-vous|docteur/i.test(note.split(/[+(]/)[0])){const weekdays=['lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche'];const candidate=addDays(start,weekdays.indexOf(visitDay[1].toLowerCase()));const d=new Date(candidate+'T12:00:00Z');if(d.getUTCDate()!==+visitDay[2]||(visitDay[3]&&d.getUTCMonth()+1!==+visitDay[3]))throw Error(`Ligne ${i+1} : le jour du commentaire ne correspond pas à la semaine.`);date=candidate;inferred=false}}
 if(rows.some(x=>x.date===date))throw Error(`Ligne ${i+1} : deux attributions pour le ${date}. Corrigez le doublon.`);rows.push({date,weekStart:weekly?start:undefined,name,note,cancelled,inferred,sourceRow:i+1});
 }
 if(!rows.length)throw Error('Aucune ligne datée exploitable.');const names=[...new Set(rows.filter(r=>!r.cancelled).map(r=>r.name))];if(names.length>4)throw Error('Plus de quatre noms distincts : harmonisez les prénoms avant l’import.');return {rows:rows.sort((a,b)=>a.date.localeCompare(b.date)),warnings,names};
}
export async function readPlanningFile(file:File):Promise<Record<string,unknown[][]>>{
 if(file.size>5*1024*1024)throw Error('Le fichier doit faire moins de 5 Mo.');const ext=file.name.split('.').pop()?.toLowerCase();if(['csv','tsv','txt'].includes(ext||''))return {[file.name]:delimited(await file.text())};if(!['xlsx','ods','docx'].includes(ext||''))throw Error('Formats acceptés : .xlsx, .ods, .csv, .tsv, .docx. Pour .xls, enregistrez d’abord en .xlsx.');
 const bytes=await file.arrayBuffer();checkZipSize(bytes);const {default:JSZip}=await import('jszip');const zip=await JSZip.loadAsync(bytes);const sheets:Record<string,unknown[][]>={};
 if(ext==='xlsx'){const {Workbook}=await import('exceljs');const wb=new Workbook();await wb.xlsx.load(bytes);wb.eachSheet(s=>{const grid:unknown[][]=[];s.eachRow({includeEmpty:true},r=>{grid.push(Array.from({length:Math.min(s.columnCount,30)},(_,i)=>{const cell=r.getCell(i+1);const v=cell.value;if(v instanceof Date)return v;if(v&&typeof v==='object'&&'formula' in v)return v.result;if(v&&typeof v==='object'&&'richText' in v)return v.richText.map(t=>t.text).join('');return v??''}))});sheets[s.name]=grid});return sheets}
 const path=ext==='ods'?'content.xml':'word/document.xml';const entry=zip.file(path);if(!entry)throw Error('Le document ne contient pas de tableau exploitable.');const xml=new DOMParser().parseFromString(await entry.async('string'),'application/xml');if(xml.getElementsByTagName('parsererror').length)throw Error('Document XML invalide.');
 if(ext==='docx'){Array.from(xml.getElementsByTagNameNS('*','tbl')).forEach((t,i)=>{sheets[`Tableau ${i+1}`]=Array.from(t.getElementsByTagNameNS('*','tr')).map(r=>Array.from(r.children).filter(c=>c.localName==='tc').map(c=>Array.from(c.getElementsByTagNameNS('*','t')).map(p=>p.textContent||'').join(' ')))});return sheets}
 const ns='urn:oasis:names:tc:opendocument:xmlns:table:1.0';const office='urn:oasis:names:tc:opendocument:xmlns:office:1.0';Array.from(xml.getElementsByTagNameNS(ns,'table')).forEach(t=>{const grid:unknown[][]=[];for(const r of Array.from(t.getElementsByTagNameNS(ns,'table-row'))){const values:unknown[]=[];for(const cell of Array.from(r.children)){if(!['table-cell','covered-table-cell'].includes(cell.localName))continue;const value=cell.getAttributeNS(office,'date-value')||Array.from(cell.getElementsByTagNameNS('*','p')).map(p=>p.textContent||'').join('\n');const count=Math.min(Number(cell.getAttributeNS(ns,'number-columns-repeated')||1),30-values.length);for(let j=0;j<count;j++)values.push(value);if(values.length>=30)break}const repeated=Number(r.getAttributeNS(ns,'number-rows-repeated')||1);if(values.some(v=>clean(v))){if(grid.length+repeated>1002)throw Error('Limite : 1 000 lignes.');for(let j=0;j<repeated;j++)grid.push(values)}else if(grid.length<1002)grid.push(values)}sheets[t.getAttributeNS(ns,'name')||'Feuille']=grid});return sheets;
}
// Read the ZIP central directory before decompression; reject oversized archives.
export function checkZipSize(buffer:ArrayBuffer){const view=new DataView(buffer);let total=0,count=0;for(let i=Math.max(0,buffer.byteLength-65557);i<=buffer.byteLength-22;i++){if(view.getUint32(i,true)!==0x06054b50)continue;const entries=view.getUint16(i+10,true);let p=view.getUint32(i+16,true);if(entries>2000)throw Error('Archive trop volumineuse.');for(let n=0;n<entries;n++){if(p+46>buffer.byteLength||view.getUint32(p,true)!==0x02014b50)throw Error('Archive invalide.');total+=view.getUint32(p+24,true);count++;p+=46+view.getUint16(p+28,true)+view.getUint16(p+30,true)+view.getUint16(p+32,true)}if(total>25*1024*1024||!count)throw Error('Le document décompressé dépasse 25 Mo.');return}throw Error('Archive ZIP invalide.')}
